# Generated by Django 4.2.14 on 2024-11-07 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('IT', 'Italian')], default='EN', max_length=2)),
            ],
        ),
    ]
