# Generated by Django 4.2.14 on 2024-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('French', 'Fr'), ('English', 'En'), ('Italian', 'It')], default='English', max_length=10),
        ),
    ]
