# Generated by Django 4.2.14 on 2024-11-07 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('French', 'Fr'), ('English', 'En'), ('Italian', 'It')], max_length=10),
        ),
    ]
