# Generated by Django 4.2.14 on 2024-11-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_age_alter_blog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
