# Generated by Django 4.2.14 on 2024-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('IT', 'Italian')], default='EN', max_length=10),
        ),
    ]
